#! /bin/bash

set -x

# Parse options
export BATCH_MODE=false
while [[ "$1" == --* ]]; do
  case "$1" in
    --batch) BATCH_MODE=true; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# TODO this only works in a new shell, do a source?
# TODO or just the mvn commands
# or a pre-script?
# curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkiverse/roq/
# curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force roq@quarkiverse/quarkus-roq

export project_dir=$1
export tools_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export tmp_dir=~/tmp

(
cd ${project_dir}

# Fetch latest from all remotes before resetting
git fetch origin
git fetch upstream

# Reset to upstream/main
git reset --hard upstream/main

# Remove untracked files and directories
git clean -fd
rm -rf target/ _site/

# Cherry-pick unmerged branch commits to validate conversion handles real changes.
# Skipped: roq-conversion (is the conversion itself), branches already in upstream/main,
# and duplicate commits across branches.

# --- Content/link fixes ---

# Work around lack of os-specific download endpoints (fix-dead-podman-links)
git cherry-pick a8dea27321 || git cherry-pick --abort

# Include more blog posts in RSS feed (test/rss-feed-all-posts)
git cherry-pick 64e7dcdec5 || git cherry-pick --abort

# --- add-external-link-checking chain (must be in order, all touch LinkCrawlerTest.java) ---

# Confirm 0s are redirects
git cherry-pick 0c196e84d6 || git cherry-pick --abort

# Add scheduled CI job to check external links and raise defects
git cherry-pick c4abc2ef1b || git cherry-pick --abort

# Tune external link checker: treat 403 as OK for medium.com, add example URLs
git cherry-pick c9b6585113 || git cherry-pick --abort

# Add linkedin/pexels to DO_NOT_CHECK, infoq.com 405 handling
git cherry-pick 6420f4542b || git cherry-pick --abort

# Fix up from bad merge
git cherry-pick ed064fdce7 || git cherry-pick --abort

# --- CI infrastructure (all touch build.yml, order matters) ---


# CI: make site output directory configurable (ci-flexible-site-dir)
git cherry-pick 121c20fbf7 || git cherry-pick --abort

# CI: make site statics directory configurable (ci-flexible-statics-dir)
git cherry-pick eaafef317b2155c53fb35943d987af4a1dc54d32 || git cherry-pick --abort
# CI: make site assets directory configurable (ci-flexible-statics-dir)
git cherry-pick 029beddd2e3d63c315540c10ff7398ea8b688b71 || git cherry-pick --abort
git cherry-pick f3e489ba412ab9e5a4ff70eb89aebabd9cdedb2a || git cherry-pick --abort


# CI: allow build to continue if Java tests fail (ci-continue-on-test-failure)
git cherry-pick 4433e5d095 || git cherry-pick --abort

# CI: add test report summary to job output (ci-test-report)
git cherry-pick 3e42a6eab8 || git cherry-pick --abort

# --- Playwright test branches (independent of each other) ---

# Add page title sanity check tests (test/page-title-sanity)
git cherry-pick 61b89ca49e || git cherry-pick --abort

# Add mobile navigation tests (test/mobile-navigation)
git cherry-pick ac3436624a || git cherry-pick --abort

# Add fragment anchor validation test (test/fragment-anchor-validation)
git cherry-pick 020721c917 || git cherry-pick --abort

# Add blog page content tests (test/blog-page-content)
git cherry-pick 74897e26c4 || git cherry-pick --abort

# Add insights page content tests (test/insights-page-content)
git cherry-pick cf5614e820 || git cherry-pick --abort

# Add working groups page content test (test/working-groups-content)
git cherry-pick 1f8d8f3daf || git cherry-pick --abort

# Sanitise some background-image urls
git cherry-pick ee4e5ab34f268c2e5656b5f4d5f38f3433ba0002 || git cherry-pick --abort
)

# TODO manually hack the stylesheet
cp ${tools_dir}/hacked-css ${project_dir}/assets/css/main.scss

mv ${project_dir}/_sass/includes/brand.css ${project_dir}/_sass/includes/brand.scss


# TODO make this generic
sed -i '' 's|href="{{ '"'"'/assets/css/main.css'"'"' | relative_url }}?2021-07-29"|href="static/bundle/app.css"|g' ${project_dir}/_layouts/base.html
#sed -i '' -e "@{{ '/assets/css/main.css' | relative_url }}?2021-07-29/@/static/bundle/app.css@" ${project_dir}/_layouts/base.html
# TODO regular expressions are hard, sed is hard, previous regexp does not work
sed -i '' -e 's|<head>|<head>  <link rel="stylesheet" href="/static/bundle/app.css" />|g' ${project_dir}/_layouts/base.html



# TOD jekyll accepts position as a mixin name, roq scss does not
find ${project_dir}/_sass -name '*.scss' -exec \
    sed -i '' -e 's|@mixin position|@mixin hackposition|g' {} +
find ${project_dir}/_sass -name '*.scss' -exec \
    sed -i  '' -e 's|@include position|@include hackposition|g' {} +

# Do a brutal sanitisation of scss that doesn't bundle cleanly TODO
find ${project_dir}/_sass -name '*.scss' -exec \
    sed -i '' 's|(\$baseurl|("http://localhost:8090/"|g' {} +
find ${project_dir}/_sass -name '*.scss' -exec \
    sed -i '' 's|:\(.*\)\$|:\1|g' {} +
find ${project_dir}/_sass -name '*.scss' -exec \
    sed -i '' 's|@mixin hackposition($pos: relative, $top: null, $right: null, $bottom: null, left: null) {|@mixin hackposition($pos: relative, $top: null, $right: null, $bottom: null, $left: null) {|g' {} +

# TODO need to handle qute stuff
## Hack: delete files with Qute example code that the Qute parser would interpret as real template syntax
rm ${project_dir}/_posts/2020-02-24-qute.adoc
rm ${project_dir}/_posts/2022-06-21-qute-templates-from-db.adoc
rm ${project_dir}/_posts/2023-10-10-intellij-quarkus-recap.adoc
rm ${project_dir}/_posts/2025-12-15-quarkus-feature-flags.asciidoc

# Delete Jekyll includes too complex for auto-conversion (allejo/jekyll-toc: pure-Liquid
# TOC generator using capture-concatenation, continue, slice, times, minus, etc.)
rm -f ${project_dir}/_includes/templates/toc.html

${tools_dir}/roq-it-jekyll ${project_dir}

# Add e2e profile to pom.xml (excludes e2e-tagged tests by default, profile enables them)
sed -i '' '/<artifactId>maven-surefire-plugin<\/artifactId>/{
N
N
s|<configuration>|<configuration>\
                    <excludedGroups>e2e</excludedGroups>|
}' ${project_dir}/pom.xml

sed -i '' '/<profiles>/a\
\        <profile>\
\            <id>e2e</id>\
\            <build>\
\                <plugins>\
\                    <plugin>\
\                        <artifactId>maven-surefire-plugin</artifactId>\
\                        <configuration>\
\                            <groups>e2e</groups>\
\                            <excludedGroups combine.self="override"/>\
\                        </configuration>\
\                    </plugin>\
\                </plugins>\
\            </build>\
\        </profile>
' ${project_dir}/pom.xml


if [ "${BATCH_MODE}" = "true" ]; then
    # Install Playwright browsers
    (cd ${project_dir} && mvn exec:java -e -Dexec.classpathScope=test \
        -Dexec.mainClass=com.microsoft.playwright.CLI \
        -Dexec.args="install --with-deps chromium")

    # Kill anything already on port 8090
    lsof -ti:8090 | xargs kill 2>/dev/null || true
    sleep 1

    # Start dev server in background on port 8090
    (cd ${project_dir} && mvn quarkus:dev -Dquarkus.http.port=8090 \
        > ${tmp_dir}/roq-server.log 2>&1) &
    SERVER_PID=$!
    timeout 120 bash -c 'until curl -sf http://localhost:8090 > /dev/null 2>&1; do sleep 1; done'
    echo "Dev server started (PID $SERVER_PID)"

    # Run tests against the dev server
    # Use a separate Maven invocation with -pl to avoid stomping the dev server's target/
    (cd ${project_dir} && mvn -B surefire:test -Dtest.url=http://localhost:8090) || true

    kill $SERVER_PID 2>/dev/null
    wait $SERVER_PID 2>/dev/null
fi
